### ISSUE TITLE
Suggestion: using ghauth

### ISSUE THREAD

**Issue by jasnell** [joyeecheung/node-core-utils#1]
The existing https://www.npmjs.com/package/ghauth module would likely make the github authentication bits easier here. It is used by some of the other command line tools we use already (like `make-node-meeting`)

**Comment by MylesBorins** [comment]
I could take a stab at this refactor if @joyeecheung is up for it

**Comment by joyeecheung** [comment]
@jasnell Wow, didn't know about this before (I blame google search), thanks!

@MylesBorins Yes go ahead, I guess that just requires some refactoring of `lib/auth.js` and `lib/request.js` (also maybe `bin/metadata.js`)

**Comment by addaleax** [comment]
Fwiw I didn’t see this issue and went ahead to open https://github.com/joyeecheung/node-core-utils/pull/5, feel free to close that if this is a better fit :)

**Comment by jasnell** [comment]
well... ghauth is fairly old (but well tested...) it might make sense to use an updated version that is based on the improvements you've made in #5.
