### ISSUE TITLE
feature: --help command arg

### ISSUE THREAD

**Issue by Tiriel** [joyeecheung/node-core-utils#22]
Opening this issue to start working on the `--help` command arg and help define what needs to be shown with it.

For now, what I see:
- [ ] Add `yargs`
- [ ] General name and purpose of the command
- [ ] Basic usage example
- [ ] Arguments details

Please feel free to complete task list!
As of now, WIP!

**Comment by MylesBorins** [comment]
Moving to an argument parser like yargs would get us a help command for free 🎉🎉🎉

**Comment by Tiriel** [comment]
Awesome! I hadn't looked yet for packages, I didn't knew this.

And it would really for another feature I had in mind (and submitted to @joyeecheung ): allowing the user to submit ***only*** the PR url and extract  the PR Id (already implemented), repo and owner (new) from it.

Thanks a lot!

**Comment by targos** [comment]
+1 for using yargs

**Comment by joyeecheung** [comment]
> allowing the user to submit only the PR url and extract the PR Id (already implemented), repo and owner (new) from it.

@Tiriel  hmm...why would we disable other options tho? I usually prefer defaults for `nodejs/node`(`get-metadata 12345`) because that's what I use the most.

**Comment by Tiriel** [comment]
@joyeecheung Sorry, my intent wasn't clear.

I don't want to disable any option, just want to enable the possibility to provide only the url and no other arguments, and have the url parsed, OR provide all the combination actually implemented.

More clearly, juste want to add an option. No option should be removed!

**Comment by joyeecheung** [comment]
@Tiriel Do you mean subtract owner and repo from `get-metadata https://github.com/<owner>/<repo>/pull/15565`? Yes that would be great!

**Comment by Tiriel** [comment]
That's precisely the idea, yup!

Usage would then be :
`get-metadata <id-or-url> [<owner> <repo>]`
If called with url, `id`, `owner` and `repo` would be extracted from it
If called with integer id, `owner` and `repo` would have to be given as args or else would default to `nodejs` and `node` respectively.

**Comment by Tiriel** [comment]
Extracting last comment to new issue!

**Comment by joyeecheung** [comment]
Can be closed now that https://github.com/joyeecheung/node-core-utils/pull/30 has landed
