### ISSUE TITLE
feature: improved url parsing to determine owner and repo of PR

### ISSUE THREAD

**Issue by Tiriel** [joyeecheung/node-core-utils#25]
Feature idea:
There's a good base in `bin/metadata.js:parsePRId` (lines 72 -78), but I think we could do more and directly parse the url for owner and repo, without removing actual options.

Usage would then be :
`get-metadata <id-or-url> [<owner> <repo>]`
If called with url: `id`, `owner` and `repo` would be extracted from it
If called with integer id: `owner` and `repo` would have to be given as args or else would default to `nodejs` and `node` respectively.

Todo:
- [ ] When first arg is url, extract owner, repo, and pr-id from it
- When first arg is integer:
  - [ ] Check second arg for owner and third arg for repo if given
  - [ ] Default owner to `nodejs` and repo to `node` if not
  - [ ] Allow args to be given in any other order when named? (`--repo=node --owner=nodejs`)

Feel free to add things!

**Comment by Tiriel** [comment]
Following discussion in #30 I'm starting a test file for functional cli testing.

It will live in `tests/functional/index.js` and will cover the functionalities described in the checkboxes.
in bdd-style specs:

`get-metadata` should:
- [ ] throw when called without arguments/with non-url string argument
- When given numeric first argument :
  - [ ] get PR from `nodejs/node` if no other arguments
  - [ ] get PR from `nodejs` as owner if second string argument is given
  - [ ] get PR from owner given as second argument and repo given as third argument
  - [ ] get PR from owner given as `-o/--owner` flag argument and repo given as `-r/--repo` flag argument
- [ ] get PR from url when given as only argument by extracting owner, repo and PR id
- [ ] throw if given url as first argument and other args are given

@joyeecheung is that ok for you?

**Comment by joyeecheung** [comment]
@Tiriel SGTM, although I think you can just put it under `test/intergration`? Also if we don't mock the authentication part then it would be a bit harder to put it on CI.

**Comment by Tiriel** [comment]
No problem, I'll put it in `test/integration`!

As for the mocking part, do you think it possible to use env vars to create a temporary `.ncurc` file with auth informations? I know secured env vars can be defined in Travis CI, I just don't know about the mocking file part...

**Comment by joyeecheung** [comment]
@Tiriel An easier way to test the CLI would be to export a function that use yargs to parse a string if given, or `process.argv` otherwise, and returns an object with all the options that we want. That way you will only need to test stuff like `assert.deepStrictEqual(parseArgs('-o=sth -r=sth'), {owner: 'sth', 'repo': 'sth'})` and test for errors and stdout (maybe need to fork another process to test erroneous inputs). Also in that case you can put it in `test/unit` since it does not actually fire any requests.

You can pass a string to `yargs` to get it parse that instead of `process.argv`( take a look at [their tests](https://github.com/yargs/yargs/blob/master/test/usage.js#L23))

Also I am thinking about refactoring the binary file a bit so we can put all data in one object and stub methods for tests.

```js
// parseArgs parse string with yargs if given, or process.argv if not
var args = parseArgs();
// Stub methods e.g. data.getReviews,  that returns fixtures wrapped in promises
run(args, data, logger, analyzers);
// Check if stubs are properly called, loggers have proper logs.
```

**Comment by Tiriel** [comment]
Okay, I think I see what you mean. More like unit-testing only the args processing part than the actual calls, since we already know they work and are tested elsewhere?

As for the bin refactoring it does seem good to me, but I think I'll stay on the url parsing + testing for this issue/PR and leave to another one, I feel I already have to much changes in one PR. Would that be ok to you?

**Comment by joyeecheung** [comment]
I think we can close this now that https://github.com/joyeecheung/node-core-utils/pull/30 has landed. Thanks!
