### ISSUE TITLE
Improve code coverage

### ISSUE THREAD

**Issue by alopezsanchez** [joyeecheung/node-core-utils#26]
Hello! I just posted here: https://github.com/nodejs/automation/issues/4#issuecomment-340605917.

I think a good way to get started and understand the code is play with it and make some tests.
So, if it seems good to you, I can improve the code coverage.

Regards.

**Comment by joyeecheung** [comment]
@alopezsanchez Hi, thank you for jumping in to help! Would love to see more code coverage, but I will need to give you a heads up that the internal API is still changing as we are fixing more todos, so there might be conflicts if there are too many people working on it at the same time. I am not warning people off, just a heads up, feel free to open PRs and see how it goes! (Hopefully it would be easier when the features stabilize or got split out into different targets.)

**Comment by joyeecheung** [comment]
P.S. I have a WIP coverage PR for `PRChecker` right now, but from what I can tell the `lib/logger` would need a bit more tests as well.

**Comment by joyeecheung** [comment]
Also if you have not contributed to Node.js core before, another way to help understand the code is to take a loot at the [collaborator guide](https://github.com/nodejs/node/blob/master/COLLABORATOR_GUIDE.md) and the [contributing guide](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md), it would be a bit harder to understand the checks without reading those.

**Comment by alopezsanchez** [comment]
Okay, I will take a look to it as soon as posible. Thank you!

I have a question about the code. Why are you using `Mocha`?. Don't you prefer `Jest`?

**Comment by joyeecheung** [comment]
@alopezsanchez Because with jest I would need to use their assertions to get object diffs...I would prefer just using the assert core module instead, less context switch when working on core.

**Comment by joyeecheung** [comment]
I think this can be closed for now since the coverage looks OK. We will need to find a way to do intergration test and cover `request.js` though, I have some ideas.
