### ISSUE TITLE
Merge policy

### ISSUE THREAD

**Issue by Tiriel** [joyeecheung/node-core-utils#55]
Quick question here, mainly for @joyeecheung :D

What is your preferred merge policy for PRs?
Do we stick to Node Core policy? (no using the "green button", etc etc)?
Do you prefer to review every PR and merge them yourself?

**Comment by refack** [comment]
I'm +1 for squash-merge and rebase-merge

**Comment by joyeecheung** [comment]
I don't think we need to stick to Node core policy, that's probably too complicated for a tool like this :D. At the moment my policy is: CI is happy, no one requested changes in half a day or it's trivial enough, then merge (wo so don't need wait for 48 hours in this repo lol).

Also I like the buttons as well. Collaborators can merge them without me reviewing of course! Although I do want to review changes that are significant.

**Comment by Tiriel** [comment]
I guess this can be closed now.

Anyway, issue can be reopend if need be.
