### ISSUE TITLE
todo: account LGTM in "COMMENTED" reviews

### ISSUE THREAD

**Issue by joyeecheung** [joyeecheung/node-core-utils#67]
Example: https://github.com/nodejs/node/pull/16248#pullrequestreview-74093431

**Comment by Tiriel** [comment]
Just to be sure, you want to count the number of "LGTM" in the comments of a review?

Anyway, I'm taking this one!

**Comment by joyeecheung** [comment]
@Tiriel I mean the LGTM in a COMMENTED review should count as an approval ;)

**Comment by Tiriel** [comment]
Oh yeah I see, sorry. 

Got it! I'll assign myself if it's ok

**Comment by Tiriel** [comment]
Landed in #72 !
